config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "artists#index"

  resources :artists do
    resources :songs, only: [:new, :create]
  end

  resources :songs, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
has_many :songs
validates :name, presence: true, uniqueness: true
validates :image_path, presence: true
end

app/models/song.rb
class Song < ApplicationRecord
belongs_to :artist
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

  def index
    @artists = Artist.all
  end

  def new
    @artist = Artist.new
  end

  def edit
    @artist = Artist.find(id)
  end

  def update
    @artist = Artist.find(id)
    @artist.update_attributes(artist_params)
    redirect_to artist_path(@artist)
  end

  def show
    @artist = Artist.find(id)
  end

  def create
    @artist = Artist.new(artist_params)
    if @artist.save
      redirect_to artist_path(@artist)
    else
      render :new
    end
  end

  def destroy
    artist = Artist.find(id)
    artist.delete
    redirect_to artists_path
  end


  private

  def artist_params
    params.require(:artist).permit(:name, :image_path)
  end

  def id
    params.require(:id)
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  def index
    @songs = Song.all
  end

  def show
    @song = Song.find params[:id]
    @artist = Artist.find @song.artist_id
  end

  def new
    @artist = Artist.find params[:artist_id]
    @song = @artist.songs.new
  end

  def create
    @artist = Artist.find(params[:artist_id])
    @song = @artist.songs.create(song_params)
    redirect_to song_path(@song)
  end


  private
  def song_params
    params.require(:song).permit(:song_title)
  end

  def song_id
    params(:song_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/artists/_form.html.erb
<%= form_for @artist do |f| %>
  <% if @artist.errors.any? %>
    <h2> <%= pluralize(@artist.errors.count, "error") %> prohibited this record from being saved: </h2>
    <ul>
      <% @artist.errors.full_messages.each do |message| %>
      <li><%= message %> </li>
      <% end %>
    </ul>
  <% end %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :image_path %>
  <%= f.text_field :image_path %>

  <%= f.submit %>

<% end %>

app/views/artists/edit.html.erb
<h1>Edit <%= @artist.name %> </h1>
<%= render partial: "form" %>

app/views/artists/index.html.erb
<%= link_to "New artist", new_artist_path %>

<h3>Your Artists</h3>
<ul>
  <%@artists.each do |artist|%>
  <li> <%= link_to "#{artist.name}", artist_path(artist.id) %> </li>
  <% end %>
</ul>

app/views/artists/new.html.erb
<%= render partial: "form" %>

app/views/artists/show.html.erb
<h1><%= @artist.name %></h1>
<img src=<%=@artist.image_path%>   alt= <%= @artist.name %>   />
<br>
<%= link_to "edit", edit_artist_path(@artist) %>
<%= link_to "remove artist", artist_path(@artist), method: :delete %>
<%= link_to "New song", new_artist_song_path(@artist) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MixMaster</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/songs/_form.html.erb
<%= form_for [@artist, @song] do |f|  %>

  <%= f.label :song_title  %>
  <%= f.text_field :song_title %>

  <%= f.submit  %>
<% end %>

app/views/songs/index.html.erb
<h1>All Songs</h1>
<h3><%= link_to "Add New Song", new_song_path %></h3>

<ul>
  <% @songs.each do |song| %>
  <li> <%= link_to song.name, song_path(song) %>  </li>
  <% end %>
</ul>

app/views/songs/new.html.erb
<h1>Add New Song</h1>

<%= render partial: "form" %>

app/views/songs/show.html.erb
<h3> <%= @song.song_title %></h3>
<%= link_to @artist.name, artist_path(@artist) %>